@WebApi_HostAddress = http://localhost:5151

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/gates
Accept: application/json

###
GET {{WebApi_HostAddress}}/api/gates/b871bb2b-63a1-4e24-aebe-2b71a13158f4
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/gates
Content-Type: application/json

{
  "Name": "ABaaa",
  "Type": "Entry",
  "Location": "Main Gate",
  "IsOperational": "false"
}

### Edycja istniejącej bramki
PUT {{WebApi_HostAddress}}/api/gates/7e49bff2-88f3-412d-bf48-8d843bf1da75
Content-Type: application/json

{
  "name": "Brama updated",
  "type": "Exit"
}




### Dodanie obrazu do istniejącej bramki
POST {{WebApi_HostAddress}}/api/gates/de3598c2-9143-4164-9ac0-5e97e1dcbffb/captures
Content-Type: application/json

{
  "licensePlate": "KR 12345",
  "brand": "Toyota",
  "color": "Red",
  "imagePath": "/images/kr12345.jpg"
}

### Pobranie obrazów z bramki
GET {{WebApi_HostAddress}}/api/gates/de3598c2-9143-4164-9ac0-5e97e1dcbffb/captures
Accept: application/json

### Test handlera wyjątków (podanie nieistniejącego ID bramki rzuci błąd 404 Problem Details)
GET {{WebApi_HostAddress}}/api/gates/00000000-0000-0000-0000-000000000000/captures
Accept: application/json

### Usunięcie obrazu (zastąp ID zmyślonymi poprawnymi wartościami)
DELETE {{WebApi_HostAddress}}/api/gates/90869cd3-2a84-4146-a55b-4e5f2a25612f/captures/WSTAW_TUTAJ_ID_MIGAWKI